### ISSUE TITLE
Page errors

### ISSUE THREAD

**Issue by house92** [britishcycling-oa/opendata#8] opened 2018-12-14 10:20 UTC
Not sure whether this is related to issue #4, but https://api.letsride.co.uk/public/v1/rides?afterTimestamp=1101&afterId=5590 returns an error

**Comment by dicknorris** [comment] 2018-12-14 16:17
I've also encountered this issue

**Comment by hexdoll** [comment] 2018-12-27 02:15
I'm also getting this issue. HTTP 500 on the above URL.

**Comment by domfennell** [comment] 2019-01-10 11:05
Hi @dicknorris, do you know anything about progress with this (and the endpoint in general)? Perhaps we could @ someone from British Cycling in this issue in case it has been missed?...

**Comment by nickevansuk** [comment] 2019-01-30 02:20
There’s a small bit of guidance here that might be helpful in terms of constructing JSON in PHP:

https://developer.openactive.io/publishing-data/data-feeds/implementing-rpde-feeds#php

**Comment by domfennell** [comment] 2019-02-06 13:07
Hi @sevenpointsix, just wondering if you know anything about this issue?

**Comment by chrispab** [comment] 2019-04-10 12:28
Hi folks, I'm trying to consume the data from British cycling - letsride. As others have mentioned the feed breaks where indicated in the first post.

I have tried putting a later timestamp and id in the URL to fetch data beyond the dodgy pages(500 error), it works for a couple of page requests then fails with 500 error again. 
I would really like to display their cycling opportunities on our site but the failure of the feed means this currently can't be done.
Any updates anyone?

**Comment by benjamindoe** [comment] 2019-04-29 12:00
This seems to still be an issue. Any updates?

**Comment by sevenpointsix** [comment] 2019-05-02 09:46
@benjamindoe I've spoken to British Cycling about this and they tell me that it's being investigated. I believe that B Hunter at British Cycling is your best point of contact. Please don't hesitate to get in touch with me directly if I can help at all though. cc. @chrispab

**Comment by RickCrilly** [comment] 2019-05-16 08:38
Hi @benjamindoe & @nickevansuk,

The issue has been resolved temporarily with a server config modification. The script serving the page was exceeding the 256MB memory limit by 12MB. The config change was implemented this morning to increase the memory limit on the server to 1024MB. So it should be a good while before we see an issue with this page again. 

However, it is my personal opinion that this fix hides an issue whose roots are in the code. The server config should be reverted at the earliest convenience. 

Thanks 

P.S. is the etiquette for someone else to check the fix before the issue is closed? Does this close issue #4 also?

**Comment by nickevansuk** [comment] 2019-05-16 10:17
Great thanks for the update @RickCrilly!

@domfennell, @GetTheData or anyone else are you able to verify this issue as resolved so @RickCrilly can close this?

**Comment by house92** [comment] 2019-05-16 10:51
@nickevansuk @RickCrilly I've successfully walked the entire feed. Thanks for getting that sorted!

**Comment by RickCrilly** [comment] 2019-05-16 11:33
You're Welcome. Closing issue.

**Closed as completed by RickCrilly** 2019-05-16 11:33 UTC
